# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jun 29 14:28:17 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 586)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.data_input_group_box = QtGui.QGroupBox(self.splitter)
        self.data_input_group_box.setMaximumSize(QtCore.QSize(16777215, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.data_input_group_box.setFont(font)
        self.data_input_group_box.setObjectName(_fromUtf8("data_input_group_box"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.data_input_group_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.offsetMarkerTableView = QtGui.QTableView(self.data_input_group_box)
        self.offsetMarkerTableView.setObjectName(_fromUtf8("offsetMarkerTableView"))
        self.horizontalLayout.addWidget(self.offsetMarkerTableView)
        self.off_marker_button_vlayout = QtGui.QVBoxLayout()
        self.off_marker_button_vlayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.off_marker_button_vlayout.setObjectName(_fromUtf8("off_marker_button_vlayout"))
        self.moveOffsetMarkerUpButton = QtGui.QPushButton(self.data_input_group_box)
        self.moveOffsetMarkerUpButton.setObjectName(_fromUtf8("moveOffsetMarkerUpButton"))
        self.off_marker_button_vlayout.addWidget(self.moveOffsetMarkerUpButton)
        self.moveOffsetMarkerDownButton = QtGui.QPushButton(self.data_input_group_box)
        self.moveOffsetMarkerDownButton.setObjectName(_fromUtf8("moveOffsetMarkerDownButton"))
        self.off_marker_button_vlayout.addWidget(self.moveOffsetMarkerDownButton)
        spacerItem = QtGui.QSpacerItem(28, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.off_marker_button_vlayout.addItem(spacerItem)
        self.addOffsetMarkerButton = QtGui.QPushButton(self.data_input_group_box)
        self.addOffsetMarkerButton.setObjectName(_fromUtf8("addOffsetMarkerButton"))
        self.off_marker_button_vlayout.addWidget(self.addOffsetMarkerButton)
        self.removeOffsetMarkerButton = QtGui.QPushButton(self.data_input_group_box)
        self.removeOffsetMarkerButton.setObjectName(_fromUtf8("removeOffsetMarkerButton"))
        self.off_marker_button_vlayout.addWidget(self.removeOffsetMarkerButton)
        self.horizontalLayout.addLayout(self.off_marker_button_vlayout)
        self.run_config_box = QtGui.QGroupBox(self.splitter)
        self.run_config_box.setMaximumSize(QtCore.QSize(435, 276))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.run_config_box.setFont(font)
        self.run_config_box.setObjectName(_fromUtf8("run_config_box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.run_config_box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.config_imports_hlayout = QtGui.QHBoxLayout()
        self.config_imports_hlayout.setObjectName(_fromUtf8("config_imports_hlayout"))
        self.importButton = QtGui.QPushButton(self.run_config_box)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.config_imports_hlayout.addWidget(self.importButton)
        self.exportButton = QtGui.QPushButton(self.run_config_box)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.config_imports_hlayout.addWidget(self.exportButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.config_imports_hlayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.config_imports_hlayout)
        self.config_menu_h_layout = QtGui.QHBoxLayout()
        self.config_menu_h_layout.setObjectName(_fromUtf8("config_menu_h_layout"))
        self.params_grid_layout = QtGui.QGridLayout()
        self.params_grid_layout.setObjectName(_fromUtf8("params_grid_layout"))
        self.nItersLineEdit = QtGui.QLineEdit(self.run_config_box)
        self.nItersLineEdit.setObjectName(_fromUtf8("nItersLineEdit"))
        self.params_grid_layout.addWidget(self.nItersLineEdit, 0, 0, 1, 1)
        self.nItersLabel = QtGui.QLabel(self.run_config_box)
        self.nItersLabel.setObjectName(_fromUtf8("nItersLabel"))
        self.params_grid_layout.addWidget(self.nItersLabel, 0, 1, 1, 1)
        self.zeroOffsetLineEdit = QtGui.QLineEdit(self.run_config_box)
        self.zeroOffsetLineEdit.setObjectName(_fromUtf8("zeroOffsetLineEdit"))
        self.params_grid_layout.addWidget(self.zeroOffsetLineEdit, 1, 0, 1, 1)
        self.zeroOffsetLabel = QtGui.QLabel(self.run_config_box)
        self.zeroOffsetLabel.setObjectName(_fromUtf8("zeroOffsetLabel"))
        self.params_grid_layout.addWidget(self.zeroOffsetLabel, 1, 1, 1, 1)
        self.randSeedLineEdit = QtGui.QLineEdit(self.run_config_box)
        self.randSeedLineEdit.setObjectName(_fromUtf8("randSeedLineEdit"))
        self.params_grid_layout.addWidget(self.randSeedLineEdit, 2, 0, 1, 1)
        self.randSeedCheckBox = QtGui.QCheckBox(self.run_config_box)
        self.randSeedCheckBox.setChecked(True)
        self.randSeedCheckBox.setObjectName(_fromUtf8("randSeedCheckBox"))
        self.params_grid_layout.addWidget(self.randSeedCheckBox, 2, 1, 1, 1)
        self.forceIncrCheckBox = QtGui.QCheckBox(self.run_config_box)
        self.forceIncrCheckBox.setObjectName(_fromUtf8("forceIncrCheckBox"))
        self.params_grid_layout.addWidget(self.forceIncrCheckBox, 3, 0, 1, 2)
        self.slipRevCheckBox = QtGui.QCheckBox(self.run_config_box)
        self.slipRevCheckBox.setObjectName(_fromUtf8("slipRevCheckBox"))
        self.params_grid_layout.addWidget(self.slipRevCheckBox, 4, 0, 1, 2)
        self.config_menu_h_layout.addLayout(self.params_grid_layout)
        self.config_vert_line = QtGui.QFrame(self.run_config_box)
        self.config_vert_line.setFrameShape(QtGui.QFrame.VLine)
        self.config_vert_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.config_vert_line.setObjectName(_fromUtf8("config_vert_line"))
        self.config_menu_h_layout.addWidget(self.config_vert_line)
        self.fit_vertlayout = QtGui.QVBoxLayout()
        self.fit_vertlayout.setObjectName(_fromUtf8("fit_vertlayout"))
        self.fit_type_label = QtGui.QLabel(self.run_config_box)
        self.fit_type_label.setObjectName(_fromUtf8("fit_type_label"))
        self.fit_vertlayout.addWidget(self.fit_type_label)
        self.linearFitRadio = QtGui.QRadioButton(self.run_config_box)
        self.linearFitRadio.setChecked(True)
        self.linearFitRadio.setObjectName(_fromUtf8("linearFitRadio"))
        self.fitTypeButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.fitTypeButtonGroup.setObjectName(_fromUtf8("fitTypeButtonGroup"))
        self.fitTypeButtonGroup.addButton(self.linearFitRadio)
        self.fit_vertlayout.addWidget(self.linearFitRadio)
        self.piecewiseFitRadio = QtGui.QRadioButton(self.run_config_box)
        self.piecewiseFitRadio.setObjectName(_fromUtf8("piecewiseFitRadio"))
        self.fitTypeButtonGroup.addButton(self.piecewiseFitRadio)
        self.fit_vertlayout.addWidget(self.piecewiseFitRadio)
        self.nPiecesSpinBox = QtGui.QSpinBox(self.run_config_box)
        self.nPiecesSpinBox.setMinimumSize(QtCore.QSize(148, 0))
        self.nPiecesSpinBox.setMinimum(2)
        self.nPiecesSpinBox.setMaximum(2)
        self.nPiecesSpinBox.setProperty("value", 2)
        self.nPiecesSpinBox.setObjectName(_fromUtf8("nPiecesSpinBox"))
        self.fit_vertlayout.addWidget(self.nPiecesSpinBox)
        self.cubicFitRadio = QtGui.QRadioButton(self.run_config_box)
        self.cubicFitRadio.setObjectName(_fromUtf8("cubicFitRadio"))
        self.fitTypeButtonGroup.addButton(self.cubicFitRadio)
        self.fit_vertlayout.addWidget(self.cubicFitRadio)
        self.config_menu_h_layout.addLayout(self.fit_vertlayout)
        self.verticalLayout.addLayout(self.config_menu_h_layout)
        self.run_buttons_layout = QtGui.QHBoxLayout()
        self.run_buttons_layout.setObjectName(_fromUtf8("run_buttons_layout"))
        self.runButton = QtGui.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.runButton.setFont(font)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.run_buttons_layout.addWidget(self.runButton)
        self.cancelButton = QtGui.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.run_buttons_layout.addWidget(self.cancelButton)
        self.plotButton = QtGui.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plotButton.setFont(font)
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.run_buttons_layout.addWidget(self.plotButton)
        self.verticalLayout.addLayout(self.run_buttons_layout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.vlayout_for_ipython = QtGui.QVBoxLayout()
        self.vlayout_for_ipython.setObjectName(_fromUtf8("vlayout_for_ipython"))
        self.verticalLayout_4.addLayout(self.vlayout_for_ipython)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.data_input_group_box.setTitle(_translate("MainWindow", "Data Input", None))
        self.moveOffsetMarkerUpButton.setText(_translate("MainWindow", "^", None))
        self.moveOffsetMarkerDownButton.setText(_translate("MainWindow", "v", None))
        self.addOffsetMarkerButton.setText(_translate("MainWindow", "+", None))
        self.removeOffsetMarkerButton.setText(_translate("MainWindow", "-", None))
        self.run_config_box.setTitle(_translate("MainWindow", "Run Configuration", None))
        self.importButton.setText(_translate("MainWindow", "Import", None))
        self.exportButton.setText(_translate("MainWindow", "Export", None))
        self.nItersLineEdit.setText(_translate("MainWindow", "1000", None))
        self.nItersLabel.setText(_translate("MainWindow", "Iterations", None))
        self.zeroOffsetLineEdit.setText(_translate("MainWindow", "0.", None))
        self.zeroOffsetLabel.setText(_translate("MainWindow", "Zero offset age", None))
        self.randSeedLineEdit.setText(_translate("MainWindow", "69.", None))
        self.randSeedCheckBox.setText(_translate("MainWindow", "random seed", None))
        self.forceIncrCheckBox.setText(_translate("MainWindow", "force increasing", None))
        self.slipRevCheckBox.setText(_translate("MainWindow", "slip reversals", None))
        self.fit_type_label.setText(_translate("MainWindow", "Fit Type", None))
        self.linearFitRadio.setText(_translate("MainWindow", "Linear", None))
        self.piecewiseFitRadio.setText(_translate("MainWindow", "Piecewise Linear", None))
        self.cubicFitRadio.setText(_translate("MainWindow", "Cubic Spline", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        self.cancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.plotButton.setText(_translate("MainWindow", "Plot", None))

